server:
  port: 8088

logging:
  level:
    root: ERROR
spring:
  main:
    banner:
      mode: off
  datasource:
    url: jdbc:h2:mem:lifung
    username: h2mem
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2